const actions = {
  LOAD_SKILL_LIST: 'LOAD_SKILL_LIST',
  LOADING_SKILL_LIST: 'LOADING_SKILL_LIST',
  LOAD_SKILL_LIST_SUCCESS: 'LOAD_SKILL_LIST_SUCCESS',
  LOAD_SKILL_LIST_FAILURE: 'LOAD_SKILL_LIST_FAILURE',

  LOAD_SKILL_DETAIL: 'LOAD_SKILL_DETAIL',
  LOADING_SKILL_DETAIL: 'LOADING_SKILL_DETAIL',
  LOAD_SKILL_DETAIL_SUCCESS: 'LOAD_SKILL_DETAIL_SUCCESS',
  LOAD_SKILL_DETAIL_FAILURE: 'LOAD_SKILL_DETAIL_FAILURE',
};
export default actions;
