/* USER ACTIONS */
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_OPTIMISTIC = 'DELETE_USER_OPTIMISTIC';

/* SKILL ACTIONS */
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const DELETE_SKILL_OPTIMISTIC = 'DELETE_SKILL_OPTIMISTIC';

/* HOLIDAY ACTIONS */
export const LOAD_HOLIDAYS_SUCCESS = 'LOAD_HOLIDAYS_SUCCESS';
export const CREATE_HOLIDAY_SUCCESS = 'CREATE_HOLIDAY_SUCCESS';
export const UPDATE_HOLIDAY_SUCCESS = 'UPDATE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_OPTIMISTIC = 'DELETE_HOLIDAY_OPTIMISTIC';

/* CALL API ACTIONS */
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

/* META ACTIONS */
export const LOAD_META_SUCCESS = 'LOAD_META_SUCCESS';

/* UTILITIES ACTIONS */
export const SCREEN_RESIZE = 'SCREEN_RESIZE';
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const TOGGLE_POPUP = 'TOGGLE_POPUP';
export const CALL_LOADER = 'CALL_LOADER';
export const CLOSE_LOADER = 'CLOSE_LOADER';
export const USER_TAB = 'USER_TAB';
export const DAY_OFF_TAB = 'DAY_OFF_TAB';
export const HOLIDAY_TAB = 'HOLIDAY_TAB';
export const SKILL_TAB = 'SKILL_TAB';
export const DEVICE_TAB = 'DEVICE_TAB';
export const REQUEST_DEVICE_TAB = 'REQUEST_DEVICE_TAB';
