/* USER ACTIONS */
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_OPTIMISTIC = 'DELETE_USER_OPTIMISTIC';

/* SKILL ACTIONS */
export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const DELETE_SKILL_OPTIMISTIC = 'DELETE_SKILL_OPTIMISTIC';

/* HOLIDAY ACTIONS */
export const LOAD_HOLIDAYS_SUCCESS = 'LOAD_HOLIDAYS_SUCCESS';
export const CREATE_HOLIDAY_SUCCESS = 'CREATE_HOLIDAY_SUCCESS';
export const UPDATE_HOLIDAY_SUCCESS = 'UPDATE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_OPTIMISTIC = 'DELETE_HOLIDAY_OPTIMISTIC';

/* CALL API ACTIONS */
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

/* META ACTIONS */
export const LOAD_META_SUCCESS = 'LOAD_META_SUCCESS';

/* UTILITIES ACTIONS */
export const SCREEN_RESIZE = 'SCREEN_RESIZE';
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';
export const TOGGLE_POPUP = 'TOGGLE_POPUP';
