const types = {
  USERS: 'USERS',
  USER: 'USER',
  DAYOFF: 'DAYOFF',
  DAYOFFS: 'DAYOFFS',
  HOLIDAY: 'HOLIDAY',
  HOLIDAYS: 'HOLIDAYS',
  SKILL: 'SKILL',
  SKILLS: 'SKILLS',
  DEVICES: 'DEVICES',
  DEVICE: 'DEVICE',
  REQUEST_DEVICES: 'REQUEST_DEVICES',
  REQUEST_DEVICE: 'REQUEST_DEVICE',
};

export default types;
