const constants = {
  WIDTH_SIDE_BAR: {
    FULL: '200px',
    SHORT: '56px',
  },
  LAYOUT: {
    HORIZONTAL: 'horizontal',
  },
  LAYOUT_ERROR_TEXT: {
    labelCol: {
      span: 8,
    },
    wrapperCol: {
      span: 12,
    },
  },
  LABEL: {
    DAY_OFF: 'Day off',
    DATE: 'Date',
    NAME: 'Name',
    HOLDER: 'Holder',
    STATUS: 'Status',
    PO_NAME: "PO's Name",
    PO_EMAIL: "PO's Email",
    VACATION_FROM: 'Vacation Days From',
    VACATION_TO: 'Vacation Days To',
    MORINING_AFTERNOON_ALLDAY: 'Morning|Afternoon|All day',
    VACATION_TYPE: 'Vacation Type',
    REASONS: 'Reasons',
    NOTES: 'Notes',
    YOUR_PROJECT: 'Your project',
    DEVICE_NAME: 'Device name',
    EXPECTED_DELIVERY_DATE: 'Expected delivery date',
    TECHNICAL_SPECIFICATIONS: 'Technical specifications',
    NUMBER_OF_DEVICE: 'Number of device',
    EQUIPMENT_REQUIRED_REASON: 'Equipment required reason',
  },
  GRID_COL: {
    GRID_COL_4: 4,
    GRID_COL_5: 5,
    GRID_COL_8: 8,
    GRID_COL_9: 9,
    GRID_COL_12: 12,
    GRID_COL_13: 8,
    GRID_COL_16: 16,
    GRID_COL_21: 21,
  },
  LABEL_COL: {
    LABEL_COL_2: 2,
    LABEL_COL_3: 3,
    LABEL_COL_4: 4,
    LABEL_COL_5: 5,
    LABEL_COL_8: 8,
  },
  WRAPPER_COL: {
    WRAPPER_COL_5: 5,
    WRAPPER_COL_10: 10,
    WRAPPER_COL_12: 12,
    WRAPPER_COL_15: 15,
    WRAPPER_COL_19: 19,
  },
  BUTTON: {
    CANCEL: 'Cancel',
    SEARCH: 'Search',
    SUBMIT: 'Submit',
    BACK: 'Back',
    ADD: 'Add new',
    EXPORT_FILE: 'Export File',
    ADD_NEW_DATE_OFF: 'Add new dayoff',
    EXPORT: 'Export',
    SAVE_AND_CONTINUE: 'Save and Cotinue',
    SAVE_AND_QUIT: 'Save and Quit',
  },
  FORMAT_DATE: 'DD-MM-YYYY',
  QUICK_CHOOSE: {
    TODAY: 'Today',
    THIS_WEEK: 'This week',
    LAST_WEEK: 'Last week',
    THIS_MONTH: 'This month',
    LAST_MONTH: 'Last month',
  },
  RADIO_CHOOSE: {
    MORNING: 'Morning',
    AFTERNOON: 'Afternoon',
    All_DAY: 'All day',
    ALL: 'All',
    ASSIGNED: 'Assigned',
    AVAILABLE: 'Available',
  },
  VACATION_TYPE: {
    ANNUAL_LEAVE: 'Annual leave',
    UNPAID_LEAVE: 'Unpaid leave',
    MATERNITY_LEAVE: 'Maternity leave',
    WEDDING_VACATION: 'Wedding vacation',
    FUNERAL_LEAVE: 'Funeral leave',
  },
  TOOLTIP: {
    PLACEMENT: {
      TOP: 'top',
    },
    TITLE: {
      EDIT: 'Edit',
    },
  },
  TABLE: {
    COLUMN_TITLE: {
      NO: 'No',
      NAME: 'Name',
      EMAIL: 'Email',
      DATE_OFF: 'Date Off',
      TYPE: 'Type',
      PO_NAME: "PO's Name",
      ACTION: 'Action',
    },
    COLUMN_FIXED: {
      RIGHT: 'right',
      LEFT: 'left',
      CENTER: 'center',
    },
  },
};

export default constants;
