const actions = {
  LOAD_USER_LIST: 'LOAD_SKILL_LIST',
  LOADING_USER_LIST: 'LOADING_SKILL_LIST',
  LOAD_USER_SUCCESS: 'LOAD_SKILL_LIST_SUCCESS',
  LOAD_USER_FAILURE: 'LOAD_SKILL_LIST_FAILURE',
};
export default actions;
